addons:
  artifacts:
    s3_region: "eu-west-1"
language: node_js
cache:
  directories:
  - node_modules
notifications:
  webhooks:
    urls:
      - http://github-webhooks.eb.dev.dadi.technology/travis-webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  email: false
  slack: false
node_js:
- '8'
